kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - name: spark-master
          image: spark:latest            
          resources:
            requests:
              memory: "50000Mi"
              cpu: "10000m"
---
kind: Service
apiVersion: v1
metadata:
  name: spark
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: http-7077
      port: 7077
      protocol: TCP
      targetPort: 7077      
  selector:
    app: spark