kind: Deployment
apiVersion: apps/v1
metadata:
  name: Spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Spark
  template:
    metadata:
      labels:
        app: Spark
    spec:
      containers:
        - name: spark-master
          image: spark-master:latest
          ports:
            - name: ui
              containerPort: 8080
              protocol: TCP
            - name: master  
              containerPort: 7077
              protocol: TCP              
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: Spark
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: http-7077
      port: 7077
      protocol: TCP
      targetPort: 7077      
  selector:
    app: Spark