apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: gcr.io/spark-on-k8s/spark:latest
          command:
            - "/opt/spark/bin/spark-class"
            - "org.apache.spark.deploy.worker.Worker"
          args:
            - "spark://spark-master:7077"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  selector:
    app: spark-worker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
